### ISSUE TITLE
App Crashed at the start

### ISSUE THREAD

**Issue by vol24pl** [Atimca/SwiftInitGenerator#2]
macOS 10.14.6 (18G87)
Xcode Version 10.3 (10G8)

App crashes after launch.

```
Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by Atimca** [comment]
Hello, @vol24pl Thank you for the report. Unfortunately, I don't have mac os dev account. Seems, that my release built just expired. However, you can build it by yourself. All sources in this repo)
