### ISSUE TITLE
“SwiftInitGenerator” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by andreacipriani** [Atimca/SwiftInitGenerator#4]
Hey, thanks for your work on this great extension.

On Catalina I can't run it anymore:

How to reproduce:
- download release 0.1.0
- be on mac os 10.15.4
- open SwiftInitGenerator

Expected:
the extension opens

Got:

![Screenshot 2020-05-29 10 52 40](https://user-images.githubusercontent.com/536929/83273639-bc098f00-a19a-11ea-8aac-48e5ac26eaea.png)

**Comment by Atimca** [comment]
Hey @andreacipriani! Thank you for the response, I'll take a look as soon as possible.

**Comment by andreacipriani** [comment]
Thanks! Let me know if I can help

**Comment by Atimca** [comment]
@andreacipriani I've made a research and it seems, that Catalina restrictions about unidentified developers are more strict for now. If you just want to download and open the app you should follow these steps. 
https://youtu.be/T7LXprbqm3E

To avoid it as far as I understand I have to buy Apple Developer program for Mac AppStore, which I don't want to do for now. I hope you understand.

Please let me know if my answer helped you.

**Comment by andreacipriani** [comment]
Hey @Atimca, thanks for the quick reply. Sure, I just wanted to let you know to check if there was a global solution. I can actually compile the binary myself ^_^
I understand you don't want to deal with the developer program. Cheers!
